### ISSUE TITLE
Feature Request: Select template when creating new note

### ISSUE THREAD

**Issue by judisohn** [HaloGamer33/Obsidian-Fuzzy-Note-Creator#1]
First, thank you for this simple, straightforward plug-in that, for me, can replace Quick Add.

The only thing missing is the ability to select the template that will be used when creating the note. My page template is simple, with just a Properties section and a few ready headers—nothing complicated. Is this possible?

**Comment by HaloGamer33** [comment]
I'm really happy you found use out of my plug-in! That's definitely something that I can do, it may take me a few days due to my schedule, but it shouldn't take long.

**Comment by ryadaj** [comment]
I am here to support this enhancement, but also just to say that this plugin is totally amazing.

**Comment by HaloGamer33** [comment]
I'm doing some re-writing of the plugin and its components, the next step is starting to work on how to read the templates folder.

**Comment by HaloGamer33** [comment]
Hi! I'm truly sorry for the slow development process, there were a lot of road-blocks during the process, both in the software aspect of it and personal problems that didn't allow me to work on this like I wanted, but I'm happy to say that it's finally done! It should work exactly like the built-in templates in obsidian, and if I didn't make any mistakes it should be a seamless experience. But if there is any problem, please open a new issue and I will solve it. With some of the changes I made I will be able to solve any problem that arises much more quickly.

**Comment by HaloGamer33** [comment]
Closed by 7dce182.
