### ISSUE TITLE
Feature Request: Replace default note creation behavior within file pane

### ISSUE THREAD

**Issue by technotherion** [HaloGamer33/Obsidian-Fuzzy-Note-Creator#3]
I would love to be able to replace the default behavior of creating a note using the New Note graphical button with the Fuzzy Note behavior. Ideally, pressing the New Note button would trigger the "Fuzzy Note Creator: Note in New Tab" behavior. I could also see hitting 'New Note' opening a Fuzzy Note Creator modal with all of the options being helpful.

Alternatively, having a Fuzzy Note Creator button that shows next to the graphical buttons in the Files pane would be helpful. 

Here's what I'm referring to in case there's any confusion. 
![image](https://github.com/user-attachments/assets/4e05e755-dcb2-4a59-b08c-c409430ddee2)

**Comment by HaloGamer33** [comment]
This has been added on commit: ef3ca50, the settings should be easy to understand by themselves, but the README will be updated shortly.

**Comment by technotherion** [comment]
Works perfectly!! Thank you!
