### ISSUE TITLE
Feature Request: Make current folder the first choice

### ISSUE THREAD

**Issue by CuteWaterBeary** [HaloGamer33/Obsidian-Fuzzy-Note-Creator#4]
I love the override default button functionality but the plugin doesn't give the option of {{current}} folder and this is the only thing holding me back from using it.

**Comment by HaloGamer33** [comment]
I'll be working on this as soon as I can. Could you explain a little more about how you'd like the feature to work? Just so I can implement it correctly.

**Comment by HaloGamer33** [comment]
This has been implemented on commit 1b341a5, there are two versions for this functionality, one that adds your current folder as the first recommendation on the folder selection, and another one that adds an option named (by default) "Current Folder" to the folder selection, both of them work on the same way, the difference is only aesthetic, and it comes down to preference.

The README has been updated with more details as well, but the settings descriptions on Obsidian should be enough to get an idea of what they do.

**Comment by CuteWaterBeary** [comment]
Almost perfect...

With these settings:
<img width="783" alt="Screen Shot 2024-10-24 at 7 44 26 PM" src="https://github.com/user-attachments/assets/9027242d-44f9-448c-bbe2-04664fe6bb24">

It shows up like this:
<img width="714" alt="Screen Shot 2024-10-24 at 7 52 38 PM" src="https://github.com/user-attachments/assets/16f19087-632d-4573-ba83-202be41f449c">


But the enter button does nothing
<img width="722" alt="Screen Shot 2024-10-24 at 7 46 09 PM" src="https://github.com/user-attachments/assets/3c53a982-ec2d-424d-8ac4-ec8e60ff4fef">

<img width="727" alt="Screen Shot 2024-10-24 at 7 45 58 PM" src="https://github.com/user-attachments/assets/c60e884b-ca79-4c09-93b6-cfca7a5af3d7">

With these settings:
<img width="772" alt="Screen Shot 2024-10-24 at 7 46 46 PM" src="https://github.com/user-attachments/assets/30551f17-df56-4439-9f43-22024ab61335">

It adds the current note's name as the first suggestion:
<img width="720" alt="Screen Shot 2024-10-24 at 7 46 56 PM" src="https://github.com/user-attachments/assets/2e5b1489-f031-44bb-b9df-68895b59d6c4">

But the enter button still does nothing. However, it does create a new file in all the other folders as expected.

**Comment by HaloGamer33** [comment]
I'm so sorry about this I don't know how I didn't notice it during testing, I'm working on it right now.

**Comment by HaloGamer33** [comment]
I fixed it on: dee5084, again, really sorry for the inconvenience.

**Comment by CuteWaterBeary** [comment]
Thank you so much! This plugin is perfect! 💜
